import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import http from 'node:http';
import {createStore} from '../lib/store.js';import {createBots,botState} from '../lib/bots.js';import {createRelay} from '../server.js';import {signPass} from '../lib/secure.js';
import {toProviderMessages} from '../lib/vendor/openbot/history.js';import {NO_ANSWER_CAME} from '../lib/vendor/openbot/bot-prompt.js';import {runAgentTurn} from '../lib/vendor/openbot/agent-turn.js';
import {createCloud} from '../lib/cloud.js';
const wait=async fn=>{for(let i=0;i<150;i++){if(await fn())return;await new Promise(r=>setTimeout(r,10));}throw new Error('Run did not settle');};
test('OpenBot source repairs restored tool order, preserves dialects and closes unanswered calls',()=>{
 const m=toProviderMessages({guidance:'Echo capabilities',messages:[{role:'tool',toolCallId:'a',content:'real result'},{role:'assistant',toolCalls:[{id:'a',name:'lookup',args:{q:'one'}},{id:'b',function:{name:'ask',arguments:'{}'}}]}]});assert.equal(m[1].tool_calls[0].function.name,'lookup');assert.equal(m[2].content,'real result');assert.equal(m[3].content,NO_ANSWER_CAME);assert.ok(!m.some(x=>x.content?.includes?.('computer_navigate')));
});
test('OpenBot agent loop assembles fragmented calls, streams complete text and surfaces failures/cancellation',async()=>{
 const events=[];const r=await runAgentTurn({threadId:'t',runId:'r'},async()=>(async function*(){yield {choices:[{delta:{content:'Hello ',tool_calls:[{index:0,id:'call-a',function:{name:'get_today',arguments:'{"q":'}}]}}]};yield {choices:[{delta:{content:'world',tool_calls:[{index:0,function:{arguments:'"today"}'}}]}}]};})(),e=>events.push(e));assert.equal(r.text,'Hello world');assert.deepEqual(JSON.parse(r.calls[0].args),{q:'today'});assert.equal(events.at(-1).type,'RUN_FINISHED');assert.equal(events.filter(e=>e.type==='TOOL_CALL_START').length,1);
 await assert.rejects(runAgentTurn({threadId:'t',runId:'bad'},async()=>{throw new Error('private provider data');},e=>events.push(e)));assert.equal(events.at(-1).type,'RUN_ERROR');assert.ok(!JSON.stringify(events).includes('private provider data'));
 const stop=new AbortController();stop.abort();await assert.rejects(runAgentTurn({threadId:'t',runId:'stopped'},async()=>{throw Error('must not call');},()=>{},stop.signal));
});
test('durable store lease is atomic, expires and can only be released by its owner',async()=>{
 let at=1000;const s=createStore({key:Buffer.alloc(32),now:()=>at});assert.equal(await s.acquireLease('bots','a',2),true);assert.equal(await s.acquireLease('bots','b',2),false);assert.equal(await s.releaseLease('bots','b'),0);assert.equal(await s.acquireLease('bots','b',2),false);at+=2001;assert.equal(await s.acquireLease('bots','b',2),true);assert.equal(await s.releaseLease('bots','a'),0);assert.equal(await s.releaseLease('bots','b'),1);
});
test('bot run requests are idempotent, owner-scoped, stoppable and interrupted runs never auto-replay',async()=>{
 const states=new Map();let time=1000,release,effects=0;const state=async(d,fn)=>{const st=states.get(d)??botState();states.set(d,st);return fn(st);};
 const engine=createBots({withState:state,now:()=>time,execute:async({ensure})=>{await new Promise(r=>release=r);await ensure();effects++;return {reply:'Done',actions:[]};}});
 const id=randomUUID(),body={requestId:id,botId:'research',revision:1,goal:'Check this'};await engine.run('a',body);await wait(()=>release);assert.equal((await engine.run('a',body)).repeated,true);await assert.rejects(engine.run('a',{...body,goal:'Different'}),/different task/);assert.equal((await engine.list('b')).jobs.length,0);await assert.rejects(engine.stop('b',id),/no longer/);await engine.stop('a',id);release();await wait(()=>engine.activeCount()===0);assert.equal(effects,0);assert.equal((await engine.list('a')).jobs[0].status,'stopped');
 await assert.rejects(engine.save('a',{id:'research',revision:1,name:'Hacked',role:'Role',mode:'assist'}),/built in/);const bot=await engine.save('a',{name:'My helper',role:'Read and explain my notes',mode:'research'});await assert.rejects(engine.save('a',{...bot,revision:999}),/changed/);assert.ok((await engine.list('b')).bots.every(b=>!b.custom));
 const stale={id:randomUUID(),botId:'research',goal:'old task',status:'running',createdAt:0,updatedAt:0,leaseUntil:0,worker:'previous-process',events:[]};states.get('a').jobs.push(stale);const next=createBots({withState:state,now:()=>time,execute:async()=>{effects++;return {};}});assert.equal((await next.list('a')).jobs[0].status,'interrupted');assert.equal(effects,0);
});
test('real relay bots work without Mac, preserve tool grants and isolate accounts',async t=>{
 let requests=0;const gemini={model:'fixture-model',generate:async body=>{requests++;const parts=body.contents.at(-1)?.parts??[];return {candidates:[{content:{role:'model',parts:parts.some(p=>p.functionResponse)?[{text:'Prepared a useful plan from Today.'}]:[{functionCall:{name:'get_today',args:{}}}]}}]};},embed:async()=>Array(512).fill(0)};
 const relay=createRelay({secret:'bot-test-private-secret-'.repeat(3),gemini}),server=http.createServer(relay.handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>{server.closeAllConnections();server.close();});const base=`http://127.0.0.1:${server.address().port}`;
 const a=signPass(relay.keys.pass,{device:'a'.repeat(32),gen:0,phoneOnly:true}),b=signPass(relay.keys.pass,{device:'b'.repeat(32),gen:0,phoneOnly:true});const api=async(pass,body)=>{const r=await fetch(base+'/cloud/bots',{method:body?'POST':'GET',headers:{'x-echo-pass':pass,...(body?{'content-type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json()};};
 assert.equal((await api('bad')).status,401);assert.equal((await api(a)).body.bots.length,6);const requestId=randomUUID(),run={action:'run',requestId,botId:'plan',revision:1,goal:'Plan my day'};assert.equal((await api(a,run)).status,202);await wait(async()=>['done','failed'].includes((await api(a)).body.jobs[0]?.status));const result=(await api(a)).body.jobs[0];assert.equal(result.status,'done',JSON.stringify(result));assert.match(result.result.reply,/useful plan/);assert.ok(result.events.some(e=>e.tool==='get_today'));assert.equal((await api(b)).body.jobs.length,0);assert.equal((await api(b,{action:'stop',id:requestId})).status,400);const before=requests;assert.equal((await api(a,run)).body.repeated,true);assert.equal(requests,before);assert.equal((await api(a,{...run,goal:'Wrong task'})).status,400);
});
test('a research bot cannot save memory or delegate another bot, and essential questions pause rather than claim completion',async()=>{
 let effects=0,round=0;const store=createStore({key:Buffer.alloc(32)}),seen=[];
 const gemini={model:'fixture',generate:async body=>{seen.push(body);return {candidates:[{content:{role:'model',parts:round++===0?[{functionCall:{name:'save_memory',args:{text:'must not be saved'}}},{functionCall:{name:'run_bot',args:{bot_id:'write',goal:'must not run'}}},{functionCall:{name:'ask_person',args:{question:'Which date should I use?'}}}]:[{text:'Which date should I use?'}]}}]};}};
 const cloud=createCloud({store,gemini,tools:{}}),result=await cloud.chat({text:'Research the plan',bot:{id:'research',name:'Research',mode:'research',role:'Research facts',runId:'r'},memory:{save:async()=>effects++,runBot:async()=>effects++}});
 assert.equal(effects,0);assert.equal(result.question,'Which date should I use?');assert.ok(!seen[0].tools[0].functionDeclarations.some(d=>['save_memory','run_bot'].includes(d.name)));
 const errors=seen[1].contents.flatMap(c=>c.parts).filter(p=>p.functionResponse?.response?.error);assert.equal(errors.length,2);
 const states=new Map(),engine=createBots({withState:async(d,fn)=>{const st=states.get(d)??botState();states.set(d,st);return fn(st);},execute:async()=>result});await engine.run('owner',{requestId:randomUUID(),botId:'research',revision:1,goal:'Research plan'});await wait(()=>engine.activeCount()===0);assert.equal((await engine.list('owner')).jobs[0].status,'needs-you');
 await assert.rejects(createCloud({store,tools:{},gemini:{model:'empty',generate:async()=>({candidates:[]})}}).chat({text:'Try a task',bot:{id:'research',name:'Research',mode:'research',role:'Role',runId:'r'}}),/no usable model/);
});
test('bot failure and account suspension retain honest state and block subsequent effects',async()=>{
 const state=botState();let revoked=false,release,effects=0;
 const engine=createBots({withState:async(_d,fn)=>fn(state),access:async()=>{if(revoked)throw Object.assign(Error('Account suspended.'),{kind:'input'});},execute:async({ensure,onEvent})=>{await onEvent({type:'TEXT_MESSAGE_CONTENT',delta:'Saved progress'});await onEvent({type:'TEXT_MESSAGE_END'});await new Promise(r=>release=r);await ensure();effects++;return {reply:'Should not complete'};}});
 await engine.run('owner',{requestId:randomUUID(),botId:'research',revision:1,goal:'Read notes'});await wait(()=>release);revoked=true;release();await wait(()=>engine.activeCount()===0);const job=(await engine.list('owner')).jobs[0];assert.equal(job.status,'failed');assert.equal(job.draft,'Saved progress');assert.equal(effects,0);assert.ok(!job.worker&&!job.context);
});
