import test from 'node:test';import assert from 'node:assert/strict';
import {cleanImage,searchImages} from '../lib/image-search.mjs';
const fixture={title:'File:Neural network.png',index:1,imageinfo:[{thumburl:'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ab/Neural_network.png/640px-Neural_network.png?tracking=1',thumbmime:'image/png',mime:'image/png',descriptionurl:'https://commons.wikimedia.org/wiki/File:Neural_network.png',user:'Uploader',extmetadata:{Artist:{value:'<a href="https://example.org">A Scientist</a>'},ImageDescription:{value:'<p>Artificial neural network diagram</p>'},LicenseShortName:{value:'CC BY-SA 4.0'},LicenseUrl:{value:'https://creativecommons.org/licenses/by-sa/4.0/'}}}]};
test('research pictures retain actual URLs, plain author, source and license credit',()=>{const r=cleanImage(fixture);assert.equal(r.author,'A Scientist');assert.equal(r.description,'Artificial neural network diagram');assert.equal(new URL(r.url).search,'');assert.match(r.markdown,/!\[Neural network.png\]/);assert.match(r.markdown,/A Scientist.*CC BY-SA 4.0/);assert.ok(r.markdown.includes(r.source)&&r.markdown.includes(r.licenseUrl));});
test('image discovery rejects arbitrary hosts, credentials, schemes, executable formats and missing licenses',()=>{for(const url of ['https://127.0.0.1/x.png','http://upload.wikimedia.org/wikipedia/commons/x.png','https://upload.wikimedia.org.evil.test/wikipedia/commons/x.png','https://user@upload.wikimedia.org/wikipedia/commons/x.png','https://upload.wikimedia.org:444/wikipedia/commons/x.png','https://upload.wikimedia.org/wikipedia/commons/test.svg','https://upload.wikimedia.org/private/x.png','javascript:alert(1)']){const f=structuredClone(fixture);f.imageinfo[0].thumburl=url;assert.equal(cleanImage(f),null,url);}for(const license of ['Fair use','','<script>alert(1)</script>']){const f=structuredClone(fixture);f.imageinfo[0].extmetadata.LicenseShortName.value=license;assert.equal(cleanImage(f),null);}assert.equal(cleanImage(null),null);});
test('image search uses one fixed bounded public API, caps results, handles unavailable source and cancellation',async()=>{let calls=0;const r=await searchImages('neural networks',{fetchImpl:async(url,options)=>{calls++;assert.equal(url.origin,'https://commons.wikimedia.org');assert.equal(url.searchParams.get('gsrnamespace'),'6');assert.equal(options.redirect,'error');assert.ok(options.signal);return Response.json({query:{pages:Array.from({length:8},(_,i)=>({...fixture,index:i}))}});}});assert.equal(calls,1);assert.equal(r.images.length,4);assert.match(r.note,/full credit/);const unavailable=await searchImages('AI',{fetchImpl:async()=>{throw Error('Private upstream details');}});assert.equal(unavailable.images.length,0);assert.ok(!unavailable.note.includes('Private'));const big=await searchImages('AI',{fetchImpl:async()=>new Response('x'.repeat(1000001))});assert.equal(big.images.length,0);const c=new AbortController();c.abort();await assert.rejects(searchImages('AI',{signal:c.signal,fetchImpl:async(_url,{signal})=>{signal.throwIfAborted();}}));});

import {createCloud} from '../lib/cloud.js';import {createStore} from '../lib/store.js';
test('chat and research bot can call real image discovery and retain credited Markdown deliverables',async()=>{
 for(const bot of [null,{id:'research',name:'Research',mode:'research',role:'Research AI',runId:'fixture-run'}]){
  let rounds=0;const cloud=createCloud({store:createStore({key:Buffer.alloc(32)}),tools:{imageFetch:async()=>Response.json({query:{pages:[fixture]}})},gemini:{model:'fixture',generate:async body=>{
   assert.ok(body.tools[0].functionDeclarations.some(t=>t.name==='image_search'));
   const parts=rounds++===0?[{functionCall:{name:'image_search',args:{query:'neural network diagram'}}}]:[{text:'# Neural networks\n\n'+body.contents.at(-1).parts[0].functionResponse.response.images[0].markdown}];
   return {candidates:[{content:{role:'model',parts}}]};
  }}});
  const out=await cloud.chat({text:'Research AI',bot});assert.match(out.reply,/# Neural networks/);assert.ok(out.reply.includes('640px-Neural_network.png'));assert.match(out.reply,/A Scientist.*CC BY-SA 4.0/);assert.equal(rounds,2);
 }
});
