import assert from 'node:assert/strict';import http from 'node:http';import {pathToFileURL} from 'node:url';import {join} from 'node:path';import {mkdir} from 'node:fs/promises';import {createRelay} from '../server.js';
const pw=process.env.ECHO_BROWSER_DEPENDENCIES?await import(pathToFileURL(join(process.env.ECHO_BROWSER_DEPENDENCIES,'playwright/index.mjs')).href):await import('playwright');
let release;const gemini={model:'fixture',embed:async()=>Array(512).fill(0),generate:async body=>{const p=body.contents.at(-1).parts;const text=p.find(p=>p.text)?.text||'';if(text.includes('Wait for me'))await new Promise(r=>release=r);return {candidates:[{content:{role:'model',parts:p.some(p=>p.functionResponse)?[{text:'Useful verified plan. <img src=x onerror=window.injected=true>'}]:[{functionCall:{name:'get_today',args:{}}}]}}]};}};
const relay=createRelay({secret:'private-ui-fixture-'.repeat(4),gemini,fetchJson:async()=>({})});const server=http.createServer(relay.handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`;await mkdir('/tmp/echo-bots-ui',{recursive:true});
try{for(const engine of (process.env.ECHO_BOT_BROWSERS||'chromium,webkit').split(',')){const browser=await pw[engine].launch({headless:true,...(engine==='webkit'&&process.env.ECHO_WEBKIT_EXECUTABLE?{executablePath:process.env.ECHO_WEBKIT_EXECUTABLE}:{})});try{const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true,serviceWorkers:'block'}),page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.locator('#get-started').click();await page.locator('[data-tab="more"]').click();await page.locator('[data-open="bots"]').first().click();await page.locator('#bots-member option').first().waitFor({state:'attached'});assert.equal(await page.locator('#bots-member option').count(),6);
await page.locator('#bots-goal').fill('Draft must survive polling');await page.locator('#bots-refresh').click();await page.waitForTimeout(150);assert.equal(await page.locator('#bots-goal').inputValue(),'Draft must survive polling');await page.locator('#bots-member').selectOption('plan');await page.locator('#bots-run button[type=submit]').click();await page.locator('#bots-jobs').getByText('Useful verified plan. <img src=x onerror=window.injected=true>',{exact:true}).waitFor();assert.equal(await page.locator('#bots-jobs img').count(),0);assert.equal(await page.evaluate(()=>!!window.injected),false);
await page.locator('#bots-jobs button').getByText('Follow up',{exact:true}).first().click();await page.locator('#bots-goal').fill('Explain those steps');await page.locator('#bots-run button[type=submit]').click();await page.waitForTimeout(200);await page.locator('#bots-refresh').click();await page.waitForTimeout(200);assert.ok(await page.locator('#bots-jobs').getByText('Explain those steps',{exact:true}).count());
await page.locator('#bots-add-open').click();await page.locator('#bots-name').fill('My helper');await page.locator('#bots-brief').fill('Read my notes and prepare useful summaries.');await page.locator('#bots-create button[type=submit]').click();await page.locator('#bots-member option').filter({hasText:'My helper'}).waitFor({state:'attached'});await page.locator('#bots-member').selectOption({label:'My helper'});await page.locator('#bots-edit').click();await page.locator('#bots-brief').fill('Read my notes and cite the supporting facts.');await page.locator('#bots-create button[type=submit]').click();await page.locator('#bots-role').getByText('Read my notes and cite the supporting facts.',{exact:false}).waitFor();await page.locator('#bots-remove').click();await page.waitForTimeout(200);assert.equal(await page.locator('#bots-member option').count(),6);
await page.locator('#bots-member').selectOption('research');await page.locator('#bots-goal').fill('Wait for me');await page.locator('#bots-run button[type=submit]').click();const stopped=page.waitForResponse(r=>r.url().endsWith('/cloud/bots')&&r.request().method()==='POST'&&r.request().postDataJSON()?.action==='stop');await page.locator('#bots-jobs button').getByText('Stop',{exact:true}).first().click();assert.equal((await (await stopped).json()).status,'stopped');release?.();await page.locator('#bots-refresh').click();await page.waitForTimeout(200);assert.match(await page.locator('#bots-jobs').innerText(),/stopped/);
await page.locator('#bots-target').selectOption('mac');await page.locator('#bots-status').getByText('Your Mac is offline.',{exact:false}).waitFor();await page.locator('#bots-target').selectOption('phone');await page.locator('#bots-member option').first().waitFor({state:'attached'});
for(const width of [320,390,430]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Bots fits ${engine} at ${width}`);}await page.screenshot({path:`/tmp/echo-bots-ui/${engine}.png`});assert.deepEqual(errors,[]);console.log(`PASS ${engine}: standalone Bots, task/result, safe text, preserved draft, follow-up, custom edit/remove, Stop, optional Mac and phone layout.`);await context.close();}finally{await browser.close();}}}finally{release?.();server.closeAllConnections();server.close();}
