import assert from 'node:assert/strict';import http from 'node:http';import {pathToFileURL} from 'node:url';import {join} from 'node:path';import {mkdir} from 'node:fs/promises';import {createRelay} from '../server.js';import {report,picture,assertions} from './markdown-fixture.mjs';
const pw=process.env.ECHO_BROWSER_DEPENDENCIES?await import(pathToFileURL(join(process.env.ECHO_BROWSER_DEPENDENCIES,'playwright/index.mjs')).href):await import('playwright');
const gemini={model:'fixture',embed:async()=>Array(512).fill(0),generate:async()=>({candidates:[{content:{role:'model',parts:[{text:report}]}}]})};
const relay=createRelay({secret:'private-markdown-fixture-'.repeat(4),gemini,fetchJson:async()=>({})});const server=http.createServer(relay.handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;await mkdir('/tmp/echo-markdown-ui',{recursive:true});
try{for(const engine of ['chromium','webkit']){const browser=await pw[engine].launch({headless:true,...(engine==='webkit'&&process.env.ECHO_WEBKIT_EXECUTABLE?{executablePath:process.env.ECHO_WEBKIT_EXECUTABLE}:{})});try{const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,serviceWorkers:'block'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://*.wikimedia.org/**',route=>route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64')}));await page.goto(base);await page.locator('#get-started').click();await page.locator('[data-tab="chat"]').click();await page.locator('#chat-input').fill('Research AI');await page.locator('#chat-input').press('Enter');await page.locator('.msg.echo .echo-markdown h1').waitFor();await assertions(page,'.msg.echo .echo-markdown');await page.screenshot({path:`/tmp/echo-markdown-ui/${engine}-chat.png`});
 await page.locator('[data-tab="bots"]').click();await page.locator('#bots-member option').first().waitFor({state:'attached'});await page.locator('#bots-goal').fill('Research AI with a useful picture');await page.locator('#bots-run button[type=submit]').click();await page.locator('#bots-refresh').click();await page.locator('#bots-jobs .echo-markdown h1').waitFor();await assertions(page,'#bots-jobs .echo-markdown');await page.evaluate(()=>window.fixtureImage=document.querySelector('#bots-jobs .echo-markdown img'));await page.waitForTimeout(2700);assert.ok(await page.evaluate(()=>window.fixtureImage===document.querySelector('#bots-jobs .echo-markdown img')),'unchanged polling preserves images and report DOM');
 for(const width of [320,390,430]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Markdown Bots fits ${engine} ${width}`);await page.locator('[data-tab="chat"]').click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Markdown Chat fits ${engine} ${width}`);await page.locator('[data-tab="bots"]').click();}
 await page.screenshot({path:`/tmp/echo-markdown-ui/${engine}-bots.png`});
 // A broken image replaces only its own visual; report and credits stay readable.
 await page.evaluate(()=>document.querySelector('#bots-jobs .echo-markdown img').dispatchEvent(new Event('error')));assert.equal(await page.locator('#bots-jobs .echo-image-unavailable').count(),1);assert.ok(await page.locator('#bots-jobs .echo-markdown a').count());
 // Stored chat history also gains formatting after reopening.
 await page.reload();await page.locator('[data-tab="chat"]').click();await page.locator('.msg.echo .echo-markdown h1').waitFor();await assertions(page,'.msg.echo .echo-markdown');assert.deepEqual(errors,[]);console.log(`PASS ${engine}: actual chat and bot responses, restored history, headings/emphasis/lists/table/code, safe credited images/links, image failure, speech cleanup and 320/390/430 px layouts.`);
 }finally{await browser.close();}}}finally{server.closeAllConnections();server.close();}
